#!/usr/bin/env python3
"""One-command bootstrap for a private HEADING OS data repository.

The engine clone (.heading-os) holds only code; every piece of real data — CRM,
knowledge, outputs, threads, context — lives in a SEPARATE private repo
(.heading-os-data) that the engine resolves at runtime through the data-root
seam (see scripts/utils/paths.py::get_data_root). This script stands that repo
up end to end so a new user runs ONE command instead of a dozen manual git/gh
steps:

  1. Scaffold the empty data tree + schema stamp (delegates to init-data.py, the
     single source of truth for the directory layout).
  2. Drop a .gitignore (rebuildable indexes, secrets, runtime state) and a README.
  3. git init + first commit.
  4. Create a PRIVATE GitHub repo via `gh` and wire it as origin (no push yet).
  5. Verified first push via the supervised_push primitive — bounded by
     inactivity, postcondition ahead/behind == 0 0, never a blind timeout.
  6. Print the exact HEADING_OS_DATA wiring line for the engine .env.

Prerequisites: `git` and the GitHub CLI (`gh`) installed and authenticated
(`gh auth login`). Refuses to clobber a non-empty target directory.

Usage:
  python scripts/create-data-repo.py [--path DIR] [--repo-name NAME]
                                     [--owner GH_USER] [--public]
                                     [--no-remote] [--dry-run]

Examples:
  # Default: sibling ../.heading-os-data, private repo named after the dir,
  # owner = your authenticated gh account.
  python scripts/create-data-repo.py

  # Custom location and repo name.
  python scripts/create-data-repo.py --path ~/work/my-data --repo-name my-heading-data

  # Local scaffold + git only, no GitHub repo (wire the remote yourself later).
  python scripts/create-data-repo.py --no-remote
"""

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from scripts.utils.clone_guard import require_main_clone
from scripts.utils.colors import BOLD, CYAN, GRAY, GREEN, RED, RESET, YELLOW
from scripts.utils.git_push import supervised_push
from scripts.utils.paths import DataRootError
from scripts.utils.workspace import get_workspace_root, require_outside_engine_clone

# Engine paths that must NEVER live in (or be pushed from) the data repo, plus
# the rebuildable index and runtime/secret files the data overlay deliberately
# does not track. Mirrors CLAUDE.md ("the data overlay never pushes
# .memory-index/") and the secrets policy (.env / .sessions are gitignored).
DATA_GITIGNORE = """\
# HEADING OS private data overlay — gitignore

# Rebuildable associative-memory index (regenerated by memory-index.py).
.memory-index/
.memory-index-code/

# Secrets and runtime credentials — NEVER commit these.
.env
.env.*
!.env.example
.sessions/
*.session
cookies.json

# Local runtime state.
.data/
.state/
.logs/
.sync/
__pycache__/
*.pyc
.DS_Store
"""

DATA_README = """\
# HEADING OS — private data overlay

This is the **private data repository** for a HEADING OS workspace. It holds all
real data — CRM contacts, knowledge, generated outputs, operational threads, and
context — kept deliberately separate from the public engine clone (`.heading-os`).

The engine resolves this repo at runtime through the data-root seam
(`get_data_root()`), either via the `HEADING_OS_DATA` environment variable or by
finding this directory as a sibling of the engine clone.

**This repository is private and must stay private.** It is never published and
never made public. Do not commit secrets here either — credentials live in the
engine's gitignored `.env`, not in tracked data.

Created by `scripts/create-data-repo.py`.
"""


def run(args, cwd, check=True, capture=True):
    """Run a command, returning CompletedProcess. Raises on non-zero when check."""
    return subprocess.run(
        args, cwd=str(cwd), check=check, capture_output=capture, text=True,
    )


def _have(tool: str) -> bool:
    """True if a CLI tool is on PATH.

    `shutil.which`, not `bash -lc "command -v"`. On a Windows host with no
    Git-bash on PATH, `subprocess.run(["bash", ...])` raises FileNotFoundError
    — so the PRECONDITION CHECK itself died on a traceback instead of printing
    "git is not installed", which is the one thing it exists to do. Every other
    script in this area goes out of its way to stay portable.
    """
    return shutil.which(tool) is not None


def _gh_authenticated() -> bool:
    return run(["gh", "auth", "status"], cwd=Path.cwd(), check=False).returncode == 0


def scaffold(target: Path, dry_run: bool) -> int:
    """Create the empty data tree via init-data.py (single source of the layout).

    A target that already carries the schema stamp is one WE scaffolded, so the
    run resumes instead of refusing. `init-data.py` rejects any non-empty
    directory, which made step 1 fatal on every re-run and left this a one-shot
    script: a `gh repo create` that failed on a taken name or the wrong org
    ended the bootstrap with a scaffolded tree, a git repo and no remote, and a
    second attempt died on "exists and is not empty" before reaching the two
    branches written to handle exactly that state ("Idempotent: skip init if
    already a repo", "If origin already exists ... skip creation"). Those
    branches were unreachable. The stamp is the discriminator: without it, a
    non-empty target is somebody else's directory and is still refused.
    """
    init_data = Path(__file__).resolve().parent / "init-data.py"
    if dry_run:
        print(f"{YELLOW}[dry-run]{RESET} would scaffold data tree at {target}")
        return 0
    if (target / ".schema-version").exists():
        print(f"{GRAY}data tree already scaffolded at {target}; resuming{RESET}")
        return 0
    proc = run([sys.executable, str(init_data), "--path", str(target)],
               cwd=get_workspace_root(), check=False)
    sys.stdout.write(proc.stdout)
    if proc.returncode != 0:
        sys.stderr.write(proc.stderr)
        print(f"{RED}Scaffold failed (target exists and is non-empty?).{RESET}")
    return proc.returncode


def write_repo_files(target: Path, dry_run: bool) -> None:
    """Drop the .gitignore and README that make this a self-describing repo.

    Never overwrites. Now that `scaffold` resumes an interrupted bootstrap, this
    runs a second time on a tree the operator may have edited, and a .gitignore
    they widened is not something to silently replace with the default.
    """
    if dry_run:
        print(f"{YELLOW}[dry-run]{RESET} would write .gitignore and README.md")
        return
    for name, body in ((".gitignore", DATA_GITIGNORE), ("README.md", DATA_README)):
        path = target / name
        if path.exists():
            print(f"{GRAY}kept existing{RESET} {name}")
            continue
        path.write_text(body, encoding="utf-8")
        print(f"{GREEN}wrote{RESET} {name}")


def is_repo_root(target: Path) -> bool:
    """True only when `target` is the ROOT of a git repository, not merely in one.

    `git rev-parse --is-inside-work-tree` answers "is this path inside ANY
    repository". It was read here as "is this the repository I already
    initialised", and the two differ for every path under an existing checkout.

    MEASURED 2026-09-08 in the operator's live clone. A test run with
    `--basetemp=.tmp/night-repair/pytest-bt` put every `tmp_path` inside the
    engine work tree; a test scaffolded a data overlay there and called
    `git_init_commit`. The old probe answered yes, `git init` was skipped, and
    the `git config` / `git add -A` / `git commit` below ran against THE ENGINE:
    commit `ed7cee1` on `main`, six files, two unrelated sessions' work, under a
    message describing neither. `git add -A` has been whole-tree since git 2.0,
    so the cwd being a leaf under `.tmp/` did not limit it.

    `--show-toplevel` is the right primitive because it answers with an
    IDENTITY rather than a yes/no: it prints the work-tree root of whatever
    repository contains `target`, so comparing it with `target` distinguishes
    "this is my repo" from "this is somebody else's repo that happens to
    contain me". `--is-inside-work-tree` cannot make that distinction at all,
    and no combination of its exit codes can. Resolved on both sides before the
    comparison, because git answers with a fully resolved path and `target`
    arrives however the caller spelled it.

    A non-zero exit means git declined to answer -- not a repository, or a
    dubious-ownership refusal -- and both mean "not my repo root", which is the
    safe direction: at worst a `git init` runs in a directory that is already
    one, which git reports and leaves alone.

    The same shape as `scripts/apply-wizard-answers.py`'s `--reset` gate, which
    uses the same family of probe as a REFUSAL. Same primitive, opposite
    consequence, and this site had the consequence backwards.
    """
    probe = run(["git", "rev-parse", "--show-toplevel"], target, check=False)
    if probe.returncode != 0:
        return False
    toplevel = probe.stdout.strip()
    if not toplevel:
        return False
    return Path(toplevel).resolve() == Path(target).resolve()


def git_init_commit(target: Path, dry_run: bool) -> int:
    """Initialise the repo on main and create the first commit."""
    if dry_run:
        print(f"{YELLOW}[dry-run]{RESET} would git init + commit at {target}")
        return 0
    # The commit below is `git add -A`, so it stages whatever work tree it lands
    # in. Refused HERE and not only in `main()` because tests and future callers
    # reach this function directly, and `main()`'s refusal cannot cover them.
    #
    # `require_main_clone(__file__)` is NOT a defence here and never was: the
    # 2026-09-08 incident happened IN HELM, where that guard passes cleanly. It
    # answers "which checkout am I running from", never "where am I about to
    # commit". Do not read its presence in `main()` as covering this.
    require_outside_engine_clone(target, "the data repo target")
    # Idempotent: skip init only when `target` is the root of its OWN repository.
    if not is_repo_root(target):
        run(["git", "init", "-b", "main"], target)
    # A fresh repo on a machine with no *global* git identity fails the first commit
    # with "Author identity unknown". Seed a local identity from the workspace's git
    # config (the engine/data clones set it locally), with a safe fallback.
    root = get_workspace_root()
    name = run(["git", "config", "user.name"], root, check=False).stdout.strip() or "HEADING OS"
    email = run(["git", "config", "user.email"], root, check=False).stdout.strip() or "noreply@users.noreply.github.com"
    run(["git", "config", "user.name", name], target)
    run(["git", "config", "user.email", email], target)
    run(["git", "add", "-A"], target)
    # Nothing to commit is fine on a re-run.
    status = run(["git", "status", "--short"], target).stdout.strip()
    if status:
        run(["git", "commit", "-m", "chore: initialize private data overlay"], target)
        head = run(["git", "rev-parse", "--short", "HEAD"], target).stdout.strip()
        print(f"{GREEN}committed{RESET} {head}: initialize private data overlay")
    else:
        print(f"{GRAY}no changes to commit (already initialized){RESET}")
    return 0


def create_remote(target: Path, owner: str | None, repo_name: str, private: bool, dry_run: bool) -> int:
    """Create the GitHub repo via gh and wire it as origin (no push here)."""
    slug = f"{owner}/{repo_name}" if owner else repo_name
    visibility = "--private" if private else "--public"
    if dry_run:
        print(f"{YELLOW}[dry-run]{RESET} would: gh repo create {slug} {visibility} --source . --remote origin")
        return 0
    # If origin already exists, assume the repo is wired and skip creation.
    has_origin = run(["git", "remote", "get-url", "origin"], target, check=False).returncode == 0
    if has_origin:
        url = run(["git", "remote", "get-url", "origin"], target).stdout.strip()
        print(f"{GRAY}origin already set ({url}); skipping repo creation{RESET}")
        return 0
    proc = run(
        ["gh", "repo", "create", slug, visibility, "--source", str(target), "--remote", "origin"],
        target, check=False,
    )
    sys.stdout.write(proc.stdout)
    if proc.returncode != 0:
        sys.stderr.write(proc.stderr)
        print(f"{RED}gh repo create failed.{RESET} Is `gh` authenticated (`gh auth login`)?")
        return proc.returncode
    kind = "private" if private else "PUBLIC"
    print(f"{GREEN}created{RESET} {kind} GitHub repo and wired origin: {slug}")
    return 0


def first_push(target: Path) -> int:
    """Verified first push via the supervised primitive (ahead/behind == 0 0)."""
    v = supervised_push(target, stall_window=180, label="data-repo:first-push")
    if v["state"] == "ok":
        print(f"{GREEN}pushed & verified [0 0]{RESET} {GRAY}({v['elapsed_s']}s){RESET}")
        return 0
    print(f"{RED}{v['state'].upper()} after push — {v['reason']}{RESET}")
    if v.get("tail"):
        print(f"{GRAY}{v['tail']}{RESET}")
    return 1


def print_wiring(target: Path) -> None:
    """Tell the user exactly how to point the engine at this data repo."""
    engine = get_workspace_root()
    print(f"\n{BOLD}{CYAN}== Wire the engine at this data repo =={RESET}")
    print(f"The engine finds the data repo two ways (env override wins):")
    print(f"  1. As a sibling — keep it next to the engine clone, no config needed:")
    print(f"       {GRAY}{engine.parent}/{RESET}")
    print(f"       {GRAY}├── {engine.name}/        (engine clone){RESET}")
    print(f"       {GRAY}└── {target.name}/   (this data repo){RESET}")
    print(f"  2. Explicitly — add this line to the engine's {BOLD}.env{RESET} (robust, recommended):")
    print(f"       {BOLD}HEADING_OS_DATA={target.resolve()}{RESET}")
    print(f"\n{GREEN}Done.{RESET} Verify with: {GRAY}python scripts/workspace-health.py{RESET}")


def main() -> int:
    require_main_clone(__file__)
    ap = argparse.ArgumentParser(description="Bootstrap a private HEADING OS data repository.")
    default_path = get_workspace_root().parent / ".heading-os-data"
    ap.add_argument("--path", default=str(default_path),
                    help="target directory for the data repo (default: ../.heading-os-data)")
    ap.add_argument("--repo-name", default=None,
                    help="GitHub repo name (default: the target directory name without a leading dot)")
    ap.add_argument("--owner", default=None,
                    help="GitHub owner/org (default: your authenticated gh account)")
    ap.add_argument("--public", action="store_true",
                    help="create a PUBLIC repo (default is private — almost never what you "
                         "want for data). The first push will then be REFUSED by the "
                         "remote-identity wall: only the engine may push to a public repo.")
    ap.add_argument("--no-remote", action="store_true",
                    help="local scaffold + git only; do not create a GitHub repo or push")
    ap.add_argument("--dry-run", action="store_true", help="show what would happen; make no changes")
    args = ap.parse_args()

    # Resolved to absolute, because two different working directories consume
    # this value. `init-data.py` is spawned with `cwd=get_workspace_root()`, so
    # a relative `--path mydata` scaffolded the tree at `<workspace>/mydata`,
    # while the .gitignore/README writes and every git command below ran
    # against `<caller cwd>/mydata`. Running from anywhere but the engine root
    # produced an empty scaffold in one directory and a git repo with no data
    # tree in another, and then pushed the wrong one.
    target = Path(args.path).expanduser().resolve()

    # BEFORE anything is written, because the first thing `main()` does after
    # this is scaffold a whole data tree at `target`. There is no legitimate
    # call with an engine-internal target: the data overlay is a SIBLING of the
    # engine by construction (`--path` defaults to `../.heading-os-data`), and
    # the engine is code only. A target inside the clone means either a typo or
    # a caller whose "temp" directory is not where it thinks it is, which is
    # exactly how 2026-09-08 happened.
    #
    # `require_outside_engine_clone` rather than a check written here: it is the
    # workspace's existing answer to this question (five callers already), and a
    # second copy is the one that stops being fixed.
    try:
        require_outside_engine_clone(target, "--path")
    except DataRootError as exc:
        print(f"{RED}REFUSING:{RESET} {exc}")
        return 2

    repo_name = args.repo_name or target.name.lstrip(".")
    private = not args.public

    print(f"{BOLD}{CYAN}== Bootstrap private data repo =={RESET}")
    print(f"  target:  {target}")
    print(f"  repo:    {repo_name} ({'private' if private else 'PUBLIC'})")
    if args.no_remote:
        print(f"  remote:  {GRAY}skipped (--no-remote){RESET}")

    # Preconditions (skip the gh checks when not creating a remote).
    if not args.dry_run and not _have("git"):
        print(f"{RED}git is not installed.{RESET}")
        return 2
    if not args.no_remote and not args.dry_run:
        if not _have("gh"):
            print(f"{RED}GitHub CLI (gh) is not installed.{RESET} Install it, then `gh auth login`.")
            return 2
        if not _gh_authenticated():
            print(f"{RED}gh is not authenticated.{RESET} Run `gh auth login` first.")
            return 2

    if scaffold(target, args.dry_run) != 0:
        return 1
    write_repo_files(target, args.dry_run)
    if git_init_commit(target, args.dry_run) != 0:
        return 1

    if args.no_remote:
        if not args.dry_run:
            print(f"\n{YELLOW}Local repo ready (no remote).{RESET} "
                  f"Create one later with: {GRAY}gh repo create <name> --private --source {target} --remote origin --push{RESET}")
            print_wiring(target)
        return 0

    if create_remote(target, args.owner, repo_name, private, args.dry_run) != 0:
        return 1
    if not args.dry_run:
        if first_push(target) != 0:
            return 1
        print_wiring(target)
    else:
        print(f"{YELLOW}[dry-run]{RESET} would verify-push and print wiring instructions")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
