#!/usr/bin/env python3
"""
CRM Relationship Health Scorer for 31C Workspace

Reads contact files from crm/contacts/, calculates health scores based on
last_touch dates and expected cadence, and outputs a relationship radar.

Usage:
    python scripts/crm-health.py              # print health radar to terminal
    python scripts/crm-health.py --update     # also regenerate radar table in people.md
    python scripts/crm-health.py --json       # output as JSON (for programmatic use)
"""

import argparse
import datetime as _dt
import re
import sys
from datetime import datetime, timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from scripts.utils.atomic import atomic_write_text
from scripts.utils.colors import GREEN, YELLOW, RED, GRAY, BOLD, RESET
from scripts.utils.workspace import (
    get_crm_contacts_dir, get_crm_config_path, get_people_file,
    get_workspace_root,
)
from scripts.utils.crm import (
    NO_CADENCE_TYPES,
    parse_config,
    parse_frontmatter,
    parse_commitments,
    calculate_health,
    scan_contacts,
)

WORKSPACE = get_workspace_root()

CONTACTS_DIR = get_crm_contacts_dir()
CONFIG_FILE = get_crm_config_path()
PEOPLE_FILE = get_people_file()

TODAY = datetime.now().date()


def format_terminal_report(contacts, tribe_warnings=None):
    """Format health report for terminal output."""
    red = [c for c in contacts if c["health"] == "red"]
    yellow = [c for c in contacts if c["health"] == "yellow"]
    green = [c for c in contacts if c["health"] == "green"]
    gray = [c for c in contacts if c["health"] == "gray"]

    lines = []
    lines.append(f"\n{BOLD}31C Relationship Radar{RESET}\n")

    # Tribe detection warnings (before health sections)
    if tribe_warnings:
        lines.append(f"{YELLOW}{BOLD}TRIBE DETECTION WARNINGS{RESET}")
        for w in tribe_warnings:
            lines.append(
                f"  {YELLOW}{w['name']}{RESET} ({w['company']}) - type: {w['type']} - "
                f"has @31c.io email ({w['email']}) but is NOT typed as tribe/tribe-leadership"
            )
        lines.append("")

    if red:
        lines.append(f"{RED}{BOLD}RED - Overdue{RESET}")
        for c in red:
            days_str = f"{c['days_since']} days" if c["days_since"] is not None else "no recorded touch"
            lines.append(f"  {RED}{c['name']}{RESET} ({c['company']}) - {c['type']} - {days_str} (cadence: {c['cadence']})")
        lines.append("")

    if yellow:
        lines.append(f"{YELLOW}{BOLD}YELLOW - Approaching{RESET}")
        for c in yellow:
            lines.append(f"  {YELLOW}{c['name']}{RESET} ({c['company']}) - {c['type']} - {c['days_since']} days (cadence: {c['cadence']})")
        lines.append("")

    if green:
        lines.append(f"{GREEN}{BOLD}GREEN - On Track{RESET}")
        for c in green:
            lines.append(f"  {GREEN}{c['name']}{RESET} ({c['company']}) - {c['type']} - {c['days_since']} days (cadence: {c['cadence']})")
        lines.append("")

    if gray:
        lines.append(f"{GRAY}{BOLD}GRAY - No Cadence{RESET}")
        for c in gray:
            lines.append(f"  {GRAY}{c['name']}{RESET} ({c['company']}) - {c['type']}")
        lines.append("")

    # Upcoming commitments
    upcoming = []
    for c in contacts:
        for commit in c["commitments"]:
            if commit["due"] and commit["due"] <= TODAY + timedelta(days=7):
                upcoming.append((c["name"], commit))

    if upcoming:
        lines.append(f"{BOLD}Active Commitments Due Soon:{RESET}")
        for name, commit in sorted(upcoming, key=lambda x: x[1]["due"] or TODAY):
            due_str = commit["due"].strftime("%Y-%m-%d") if commit["due"] else "no date"
            overdue = " (OVERDUE)" if commit["due"] and commit["due"] < TODAY else ""
            lines.append(f"  [ ] {name} - {commit['text']}{RED}{overdue}{RESET}")
        lines.append("")

    # Summary
    total = len(contacts)
    lines.append(f"{BOLD}Total:{RESET} {total} contacts tracked | {RED}{len(red)} red{RESET} | {YELLOW}{len(yellow)} yellow{RESET} | {GREEN}{len(green)} green{RESET}")
    lines.append("")

    return "\n".join(lines)


def generate_radar_table(contacts):
    """Generate the Contact Radar markdown table for people.md."""
    lines = []
    lines.append("## Contact Radar")
    lines.append("")
    lines.append(f"> Auto-generated by crm-health.py on {TODAY.strftime('%Y-%m-%d')}")
    lines.append("")
    lines.append("| Name | Company | Type | Last Touch | Health | CRM File |")
    lines.append("|------|---------|------|-----------|--------|----------|")

    # Sort: red first, then yellow, then green, then gray
    order = {"red": 0, "yellow": 1, "green": 2, "gray": 3}
    sorted_contacts = sorted(contacts, key=lambda c: (order.get(c["health"], 4), c["name"]))

    for c in sorted_contacts:
        health_icon = {"red": "RED", "yellow": "YELLOW", "green": "GREEN", "gray": "GRAY"}.get(c["health"], "?")
        last = c["last_touch"] if c["last_touch"] else "-"
        link = f"[crm](../crm/contacts/{c['file']})"
        lines.append(f"| {c['name']} | {c['company']} | {c['type']} | {last} | {health_icon} | {link} |")

    lines.append("")
    return "\n".join(lines)


def update_people_md(contacts):
    """Update the Contact Radar table in context/people.md."""
    if not PEOPLE_FILE.exists():
        print(f"{RED}Error: {PEOPLE_FILE} not found{RESET}")
        return False

    content = PEOPLE_FILE.read_text(encoding="utf-8")
    radar_table = generate_radar_table(contacts)

    # Remove existing radar table if present
    pattern = r"## Contact Radar\n.*?(?=\n---|\n## [^C])"
    if re.search(pattern, content, re.DOTALL):
        content = re.sub(pattern, "", content, flags=re.DOTALL)

    # Insert radar table after the header block (after first ---)
    first_sep = content.find("---", content.find("---") + 1)
    if first_sep != -1:
        insert_pos = content.find("\n", first_sep) + 1
        content = content[:insert_pos] + "\n" + radar_table + "\n" + content[insert_pos:]
    else:
        content = radar_table + "\n" + content

    atomic_write_text(PEOPLE_FILE, content)
    return True


def format_json(contacts):
    """Output contacts as JSON, including the fields /crm next ranker depends on."""
    import json
    output = []
    for c in contacts:
        # Compute days_overdue: how many days past the red threshold we are.
        # Negative or zero means within cadence; ranker filters to >0 for REDs.
        cadence = c.get("cadence", 0)
        days_since = c.get("days_since")
        if days_since is None or not cadence:
            days_overdue = 0
        else:
            days_overdue = max(0, int(days_since) - int(cadence))

        entry = {
            "name": c["name"],
            "company": c["company"],
            "email": c.get("email", ""),
            "type": c["type"],
            "stage": c.get("stage", ""),
            "last_touch": c["last_touch"],
            "cadence": cadence,
            "health": c["health"],
            "days_since": days_since,
            "days_overdue": days_overdue,
            "radar_freeze_until": c.get("radar_freeze_until", ""),
            "commitments": [
                {"text": cm["text"], "due": cm["due"].strftime("%Y-%m-%d") if cm["due"] else None}
                for cm in c["commitments"]
            ],
            "file": c["file"],
        }
        output.append(entry)
    return json.dumps(output, indent=2)


def main():
    parser = argparse.ArgumentParser(description="31C CRM Relationship Health Scorer")
    parser.add_argument("--update", action="store_true", help="Regenerate radar table in people.md")
    parser.add_argument("--json", action="store_true", help="Output as JSON")
    parser.add_argument("--demote-candidates", action="store_true",
                        help="Surface dormancy candidates (90+ days silent prospects) for approval")
    parser.add_argument("--demote-threshold", type=int, default=90,
                        help="Days silent before a contact qualifies for demotion (default 90)")
    args = parser.parse_args()

    config = parse_config(CONFIG_FILE)
    contacts, tribe_warnings, dangling_refs, _stages, _aliases = scan_contacts(config)

    # Phase 2.4: log pipeline.md companies with no matching CRM contact.
    # Helps maintain crm/aliases.md - run crm-health.py to see stale entries.
    _contact_companies: set = set()
    for _c in contacts:
        _co = (_c.get("pipeline_company", "") or _c.get("company", "")).lower().strip()
        if _co:
            _contact_companies.add(_co)
            # If the contact's company normalises through an alias (e.g., contact has
            # `company: TT` and aliases.md maps tt -> exampletelco), we add the canonical
            # form. This ensures _contact_companies matches _stages.keys() which uses the
            # canonical pipeline.md company name.
            _contact_companies.add(_aliases.get(_co, _co))
    _unmatched = set(_stages.keys()) - _contact_companies
    if _unmatched:
        _log_dir = WORKSPACE / ".sync" / "logs"
        _log_dir.mkdir(parents=True, exist_ok=True)
        _log_path = _log_dir / f"crm-unmatched-pipeline-{_dt.datetime.now().strftime('%Y-%m-%d')}.log"
        _log_path.write_text(
            "Pipeline.md companies with no matching CRM contact:\n" +
            "\n".join(f"  - {c}" for c in sorted(_unmatched)) + "\n",
            encoding="utf-8",
        )

    if dangling_refs:
        # Route to stderr so `crm-health.py --json` produces a clean JSON
        # stream on stdout (crm_next.py and any other pipeline consumer
        # parses stdout). Terminal callers still see the warning - stderr
        # mixes into the same TTY by default.
        print(f"{YELLOW}WARN: {len(dangling_refs)} contact(s) reference missing address-book entities:{RESET}", file=sys.stderr)
        for dr in dangling_refs:
            print(f"  - {dr['file']} -> entity_ref {dr['entity_ref']}", file=sys.stderr)
        print(f"  Fix: create crm/address-book/{{slug}}.md for each missing entity.", file=sys.stderr)

    if not contacts:
        print(f"{YELLOW}No contact files found in {CONTACTS_DIR}{RESET}")
        print(f"Add contacts with: /crm add [name] [company] [type]")
        sys.exit(0)

    if args.json:
        print(format_json(contacts))
    else:
        print(format_terminal_report(contacts, tribe_warnings))

    if args.update:
        if update_people_md(contacts):
            print(f"{GREEN}Radar table updated in {PEOPLE_FILE.name}{RESET}")
        else:
            print(f"{RED}Failed to update {PEOPLE_FILE.name}{RESET}")

    if args.demote_candidates:
        from scripts.utils.crm import find_dormancy_candidates
        from scripts.utils.crm_autolog import atomic_write
        from datetime import date as _date
        import re as _re
        candidates = find_dormancy_candidates(contacts, today=_date.today(), threshold_days=args.demote_threshold)
        if not candidates:
            print(f"{GREEN}No dormancy candidates - all active contacts within {args.demote_threshold}d.{RESET}")
        else:
            print(f"\n{YELLOW}{BOLD}DORMANCY CANDIDATES ({len(candidates)} contacts {args.demote_threshold}+ days silent):{RESET}")
            for c in candidates:
                name = c.get("name", c.get("slug", c["file"]))
                ctype = c.get("type", "?")
                lt = c.get("last_touch", "?")
                days = c.get("days_silent", "?")
                print(f"  {c['file']}: {name} ({ctype}) - last touch {lt} ({days} days)")
            print(f"\nTo demote: set `status: dormant` in each contact file.")
            print(f"Confirm demote all {len(candidates)} contacts to dormant? [yes/no]")
            try:
                resp = input("> ").strip().lower()
            except (EOFError, KeyboardInterrupt):
                print("\nAborted.")
                return
            if resp == "yes":
                for c in candidates:
                    path = CONTACTS_DIR / c["file"]
                    text = path.read_text(encoding="utf-8")
                    # Scope the status:-check to the frontmatter slice (text before
                    # the closing ---). Whole-file check would match body content
                    # (e.g., a `status:` literal in an interaction log entry).
                    fm_end = text.find("---", 3)
                    if fm_end == -1:
                        # No frontmatter — skip silently. Should not happen for valid
                        # relationship records but defensive.
                        print(f"  {YELLOW}[skipped]{RESET} {c['slug']}: no frontmatter")
                        continue
                    frontmatter = text[:fm_end]
                    if "status:" in frontmatter:
                        new_frontmatter = _re.sub(r"^status:.*$", "status: dormant", frontmatter, count=1, flags=_re.MULTILINE)
                        text = new_frontmatter + text[fm_end:]
                    else:
                        # Insert status field before closing --- of frontmatter
                        insert_at = text.rfind("\n", 0, fm_end)
                        text = text[:insert_at] + "\nstatus: dormant" + text[insert_at:]
                    atomic_write(path, text)
                    print(f"  {GREEN}[demoted]{RESET} {c['file']}")
                print(f"{GREEN}{len(candidates)} contacts demoted to dormant.{RESET}")
            else:
                print("No changes made.")


if __name__ == "__main__":
    main()
