#!/usr/bin/env python3
"""Regenerate ``config/ordinary-english.txt``, the content gate's ordinary-word floor.

The gate's denylist harvests real organisation names out of the private DATA
overlay. An organisation whose name reduces to one ordinary English word (see
``_org_token_forms`` in ``scripts/utils/content_denylist.py``) used to donate
that bare word as a token, and the gate then fired on every piece of engine
prose that happened to use it. This file builds the vocabulary that stops that.

The vocabulary is DERIVED, never curated. Two independent public sources, both
consulted at build time:

* a frequency-ranked unigram list of a general web corpus, used ONLY to decide
  which words are ordinary. It is not redistributed by this repository.
* an English dictionary word list, which supplies the words that are shipped.
  It is public domain (Unlicense), and the artifact is a subset of it.

Neither is a runtime dependency: this script runs by hand when the vocabulary
needs refreshing, and the committed artifact is what the gate reads.

Why two sources and not one. The frequency list alone conflates "ordinary
English" with "frequent on the web": measured 2026-09-04, two well-known
company names that are real denylist tokens on this machine rank 1335th and
20292nd in it, and a floor built on frequency alone would have stopped guarding
both. Neither is in the dictionary, so the intersection keeps them. The
dictionary alone has no notion of ordinary: it holds 370k entries including
words no reader would recognise, and those are exactly the words a distinctive
brand is named after. The intersection is what "ordinary English" means.

Where the cut falls is measured, not chosen: the frequency list is truncated at
the rank where its cumulative counts first reach ``--coverage`` of all running
English text (0.95 by default, rank 27598 as measured 2026-09-04). A word
outside that is by construction not ordinary.

Usage:
  python scripts/dev/build-ordinary-english.py            # rewrite the artifact
  python scripts/dev/build-ordinary-english.py --check    # exit 1 if it would change
"""
from __future__ import annotations

import argparse
import hashlib
import sys
import urllib.request
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

from scripts.utils.workspace import get_default_tz, get_workspace_root

FREQUENCY_URL = "https://norvig.com/ngrams/count_1w.txt"
DICTIONARY_URL = (
    "https://raw.githubusercontent.com/dwyl/english-words/master/words_alpha.txt"
)
OUT_REL = "config/ordinary-english.txt"


def _fetch(url: str) -> tuple[str, str]:
    """Return (text, sha256) for a source, so provenance is recorded, not claimed."""
    with urllib.request.urlopen(url, timeout=180) as resp:  # noqa: S310 - pinned https
        raw = resp.read()
    return raw.decode("utf-8", errors="strict"), hashlib.sha256(raw).hexdigest()


def _cut_rank(counts: list[tuple[str, int]], coverage: float) -> int:
    """The 1-based rank at which cumulative frequency first reaches ``coverage``."""
    total = sum(n for _, n in counts)
    seen = 0
    for rank, (_word, n) in enumerate(counts, 1):
        seen += n
        if seen / total >= coverage:
            return rank
    return len(counts)


def build(coverage: float) -> str:
    freq_text, freq_sha = _fetch(FREQUENCY_URL)
    dict_text, dict_sha = _fetch(DICTIONARY_URL)

    counts: list[tuple[str, int]] = []
    for line in freq_text.splitlines():
        word, _tab, num = line.partition("\t")
        if num.strip().isdigit():
            counts.append((word.strip().lower(), int(num)))
    dictionary = {w.strip().lower() for w in dict_text.split() if w.strip()}

    rank = _cut_rank(counts, coverage)
    ordinary = sorted({w for w, _ in counts[:rank] if w in dictionary and w.isalpha()})

    header = [
        "# ordinary-english.txt - the content gate's ordinary-word floor.",
        "#",
        "# GENERATED by scripts/dev/build-ordinary-english.py. Do not hand-edit:",
        "# a hand-maintained security list falls behind silently, which is the",
        "# defect this file exists to end. Read by is_ordinary_english() in",
        "# scripts/utils/content_denylist.py; nothing else consumes it.",
        "#",
        "# A word here is withheld as a BARE denylist token only when the entity",
        "# it came from still contributes a multi-word phrase token, so the match",
        "# is narrowed and never removed. See _apply_ordinary_english_floor.",
        "#",
        f"# Built: {datetime.now(get_default_tz()).date().isoformat()}",
        f"# Coverage cut: {coverage:.2%} of running English text -> rank {rank}",
        f"# Frequency source (selection only, NOT redistributed): {FREQUENCY_URL}",
        f"#   sha256 {freq_sha}",
        "# Dictionary source (public domain, Unlicense; the shipped words are a",
        f"#   subset of it): {DICTIONARY_URL}",
        f"#   sha256 {dict_sha}",
        f"# Words: {len(ordinary)}",
        "",
    ]
    return "\n".join(header + ordinary) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--coverage", type=float, default=0.95,
                    help="share of running English text the cut must cover (default 0.95)")
    ap.add_argument("--check", action="store_true",
                    help="exit 1 when the artifact would change, without writing")
    args = ap.parse_args()

    out = get_workspace_root() / OUT_REL
    built = build(args.coverage)

    if args.check:
        current = out.read_text(encoding="utf-8") if out.is_file() else ""
        # The header carries a build date and two upstream digests, so a rebuild
        # of unchanged upstreams still differs. Compare the WORDS.
        def words(text: str) -> list[str]:
            return [l for l in text.splitlines() if l and not l.startswith("#")]
        if words(current) != words(built):
            print(f"{OUT_REL}: out of date ({len(words(current))} words on disk, "
                  f"{len(words(built))} rebuilt)", file=sys.stderr)
            return 1
        print(f"{OUT_REL}: up to date ({len(words(built))} words)")
        return 0

    out.write_text(built, encoding="utf-8")
    written = [l for l in built.splitlines() if l and not l.startswith("#")]
    print(f"wrote {out} ({len(written)} words)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
